title: Add Jam
description: >
  Software product development in Glasgow. We design and build everything from the app itself to the server-side APIs and websites that support them.
email: yo@addjam.com
url: "http://addjam.com"
twitter_username: addjam
github_username: addjam
gems: [bourbon, neat, jekyll-sitemap, jekyll-minifier]
paginate: 5
paginate_path: "/blog/page:num"
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"
exclude:
  - divshot.json
