- name: LoL Newsletter
  description: Keep up to date with League of Legends. Free, weekly email and no spam.
  url: http://lolnewsletter.com
  logo: lolnewsletter.png

- name: Free Champions
  description: Get notified by email as soon as the League of Legends free champion rotation gets updated.
  url: http://freechampions.com
  logo: freechampions.png
